# Generated by Django 5.2 on 2025-04-06 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterModelOptions(
            name='assetprice',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Preço do Ativo', 'verbose_name_plural': 'Preços dos Ativos'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='check_interval',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tunnel_lower_limit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tunnel_upper_limit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assetprice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='assetprice',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='asset',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='asset',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='asset',
            name='intervalo_checagem',
            field=models.IntegerField(default=5, help_text='Intervalo de checagem em minutos', verbose_name='Intervalo de Checagem'),
        ),
        migrations.AddField(
            model_name='asset',
            name='limite_inferior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite Inferior'),
        ),
        migrations.AddField(
            model_name='asset',
            name='limite_superior',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Limite Superior'),
        ),
        migrations.AddField(
            model_name='asset',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sigla',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='assets.asset', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
    ]
