# Generated by Django 5.1.8 on 2025-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options_alter_assetprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='email_alerta',
            field=models.EmailField(blank=True, help_text='Email que receberá os alertas de preço', max_length=254, null=True, verbose_name='Email para Alertas'),
        ),
    ]
